name: JS Actions

on: pull_request
jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: haha
        uses: ./.github/actions/joke-action

      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
          joke: ${{steps.haha.conclusion}}
          issue-title: ${{steps.haha.outcome}}
          repo-token: ${{secrets.GITHUB_TOKEN}}
